### ISSUE TITLE
Freezing Problems?

### ISSUE THREAD

**Issue by ctbartolillo** [amzn/alexa-avs-raspberry-pi#11]
Is anyone having problems with the Alexa Voice Service freezing after you talk and hit stop listening?

**Comment by keithschm** [comment]
Nope. I am using a Pi 3. Works well

**Comment by ajotwani** [comment]
@ctbartolillo what model of Raspberry Pi are you using?

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue. 

Thanks!
