### ISSUE TITLE
Anybody got any idea about this java error?

### ISSUE THREAD

**Issue by olliegg123** [amzn/alexa-avs-raspberry-pi#116]
When I click the button I get a pop up saying 'line with format PCM_SIGNED 16000.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian not supported.' Any ideas?

**Comment by vlasov01** [comment]
@olliegg123 Your user needs to be part of audio group. So add your user to this group or run as root with sudo.

**Comment by olliegg123** [comment]
@vlasov01 Running all as sudo and in all groups. Same error.

**Comment by ajotwani** [comment]
@olliegg123 have you looked at this thread? https://github.com/amzn/alexa-avs-raspberry-pi/issues/50

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
