### ISSUE TITLE
Anyone has idea on how to fixed adafruit gps breakout module?

### ISSUE THREAD

**Issue by Terrence922** [amzn/alexa-avs-raspberry-pi#118]
Led on gps breakout is not blinking after connected to raspberry pi.

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
