### ISSUE TITLE
Can't obtain Authorization from Login with Amazon

### ISSUE THREAD

**Issue by ebazan** [amzn/alexa-avs-raspberry-pi#132]
At step 10.4 instead of receving a "device token ready" message I get an error fom Amazon:

**We're sorry!**
An error occurred when we tried to process your request. Rest assured we're are already working on the problem and expect to resolve it shortly.

I's now a couple of weeks from the first time but no good news.

Am I the only one?
Any suggestion?

Thank You,

            enrico

**Comment by ajotwani** [comment]
@ebazan have you looked at this? https://github.com/amzn/alexa-avs-raspberry-pi/issues/5

**Comment by viengk** [comment]
I'm at the spot as @ebazan. I've went back to double check all my entries under “Cannot connect to the Companion Service” errors and I still get the same "We're Sorry" error msg.

Anyone else run into the problem?

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!

**Comment by alok155** [comment]
I am also getting the same issue while using Authorization Code Grant because i am trying to use login with amazon on my localhost with virtual host entry.
url that i m using:
https://www.amazon.com/ap/oa?client_id='my client id'&scope='profile'&response_type='code'&state='any random integer'&redirect_uri='http://testsite.dev/index.php/welcome/amazon'

do let me know if i missed anything.
