### ISSUE TITLE
Re-authenticate Alexa Voice Service on reboot

### ISSUE THREAD

**Issue by jaysonmsaavedra** [amzn/alexa-avs-raspberry-pi#15]
So I accidentally unplugged my Echo Pi or whatever you wanna call it, and I realized setting it up again is a pain. Is there anyway I can turn the whole thing into an executable program, or anything like that? Or anywhere I can look to base that idea off of. Thanks!

**Comment by shankararunachalam** [comment]
Could you elaborate on the 'unplugged' part? I would imagine it should be a matter of running the companion service and the java client again, no?

**Comment by bgulla** [comment]
Docker would be the best way, im working on getting a working Dockerfile going now.

**Comment by rprocha** [comment]
I think Jayson is talking about the part where you need to re-authenticate the device everytime you reboot the server portion of the project. You will need to alter the server code to make the tokens persist in a file and read the tokens every time you re-start the server. That way your raspberry pi will always connect to the amazon service straight away.

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
