### ISSUE TITLE
Missing "cert" folder and it's contents

### ISSUE THREAD

**Issue by zas9vf** [amzn/alexa-avs-raspberry-pi#164]
Hey I've been trying to put Alexa on my Pi but I when I try to run the generate.sh script it error because it is trying to access the <REFERENCE_IMPLEMENTATION>/javaclient/certs for some files but the project on GH that I downloaded doesnt have that cert folder so npm start does work.

Should there be a certs folder? If not, is there some work around for this?

**Comment by erikhopf-amzn** [comment]
The certs folder is created when you run the generate script. Can you send me the error you're getting?

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
