### ISSUE TITLE
localhost says error:not found

### ISSUE THREAD

**Issue by imranraziuddin11** [amzn/alexa-avs-raspberry-pi#167]
after executing mvn exec:exec, after signing in to amazon i was redirected to local host where it says error:not found.

**Comment by swasey-amzn** [comment]
To clarify: you ran the companion service (with npm start), and the app (with mvn exec:exec) and got prompted to visit the URL of the companion service, you went there and logged in, but after you logged in it redirected you back to localhost and you received a 404 Not Found?

If that's all correct, was the companion service still running? I can imagine maybe it received some bad input and crashed, which could cause the error upon redirect in your browser. Also, can you verify that you setup your security profile information on the developer portal website appropriately so that the redirect URI is correct? Make sure you follow the instructions 100% on that or you could get the 404 you're seeing. The "Allowed Return URLs" section should have the following: **https://localhost:3000/authresponse**

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
