### ISSUE TITLE
Moving away from maven

### ISSUE THREAD

**Issue by gaurav-lagad** [amzn/alexa-avs-raspberry-pi#174]
Hi. Can we execute this project using java. if yes, can you please point us in the right direction?

Thanks!

**Comment by ajotwani** [comment]
Not sure what you mean by execute using Java. Maven is a Java tool.

**Comment by gaurav-lagad** [comment]
Hi, @ajotwani . So currently, the documentation allows us to experiment with alexa voice service on a  device using Java Client or on raspberry Pi. I want to experiment with this on Kindle device which uses armv7 architecture. We use maven to build the jars and maven exec plugin is used to execute the app. However, I wont be able to use maven on the Kindle device. I wanted some alternative method by which I can proceed ahead.
I can try and build the jars on our ubuntu system and later push it onto the device. But I am concerned on how I can execute the AVS on device. 
Please let me know if you need more clarification.Thank you for your help.

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!

**Comment by gaurav-lagad** [comment]
Hi @ajotwani ! Apologies for late reply. I have resolved this issue, I wanted to execute the program with the help of jvm and not maven. Thanks!!
