### ISSUE TITLE
X11 issue?

### ISSUE THREAD

**Issue by mmassel** [amzn/alexa-avs-raspberry-pi#188]
I've made it through step 9 but when I enter mvn exec:exec, there is a build error, which seems to have something to do with an x11 display (I think). I ran it again as mvn -X exec:exec and attached is the log.

I'm accessing the Pi through SSH on my Mac. I've got a screen share running with the Pi too with vnc://raspberrypi.local:5901.

Any help would be deeply appreciated.
Thank you.

[echo.txt](https://github.com/amzn/alexa-avs-raspberry-pi/files/280906/echo.txt)

**Comment by ajotwani** [comment]
Hi @mmassel - mvn:exec exec is not headless, and needs to be run through VNC (or a physically connected monitor).

**Comment by jamesmcn** [comment]
try using `ssh -X` to open an X11 tunnel from your Mac to your pi. Then you should be able to run `mvn exec:exec` without installing VNC.

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
