### ISSUE TITLE
Use via webcam microphone instead of usb microphone.

### ISSUE THREAD

**Issue by jimdsouza** [amzn/alexa-avs-raspberry-pi#208]
I have a Logitech Webcam C270 installed which has an embedded microphone. Can that be used instead of the USB mic? 
If yes, what settings would I have to change?

for now, when I click "Start Listening", it automatically activates "Stop Listening" by itself followed by a brief Processing time. So I only click on Start and do nothing and the process ends. I'm guessing this is because it cant detect a mic.

**Comment by bill-orange** [comment]
You are likely correct that it is not recognized as a microphone.  I tried my cheap HP camera on the PI with no success some time ago.  Just to be sure, you can go to audio settings buried in the top left menu and see if an audio device is showing up.  I discovered that is has to be set as the default.

**Comment by hankp46** [comment]
I use a webcam hooked into a usb port for my mic and use standard audio output. This is what i had to do to make it work:
Create an 'asymmetric' ALSA device that uses both cards. Something like this in ~/.asoundrc, for example:
    pcm.!default {
        type **asym**
        playback.pcm "hw:0,0"
        capture.pcm "hw:1,1"
    }

Hope this helps

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
