### ISSUE TITLE
Input/Output via USB soundcard

### ISSUE THREAD

**Issue by Bantammenace** [amzn/alexa-avs-raspberry-pi#37]
Is there an option to input/output sound via a USB soundcard ? I can only seem to get sound out to either HDMI or the 3.5mm Jack. I have a Plugable USB Audio Adapter which has a mic input (Hama Notebook mini microphone) and headphone output (has its own 3.5mm jack). I input currently using a Zoom H1 Digital Recorder in USB mode

**Comment by Sacro524** [comment]
Are you using alsa's default config? `/usr/share/alsa/alsa.conf` the values for defaults.ctl.card and defaults.pcm.card had to be changed for input/output to work on my usb sound card. You can find the value for each card via `cat /proc/asound/cards` which should most likely be 1.

**Comment by printgeek** [comment]
editing alsa.conf doesn't work in Jessie, if you are using Jessie then use this method:

http://raspberrypi.stackexchange.com/questions/40831/how-do-i-configure-my-sound-for-jasper-on-raspbian-jessie

**Comment by Kimberlyluve** [comment]
No
On Mar 28, 2016 11:06 AM, "Sacro524" <notifications@github.com> wrote:

Are you using alsa's default config? /usr/share/alsa/alsa.conf the values
for defaults.ctl.card and defaults.pcm.card had to be changed for
input/output to work on my usb sound card. You can find the value for each
card via cat /proc/asound/cards which should most likely be 1.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/amzn/alexa-avs-raspberry-pi/issues/37#issuecomment-202430629>

**Comment by Sacro524** [comment]
@printgeek it worked for me on a new Jessie installation (March 18 release) are you sure you are not thinking about the previous alsa-base.conf file

http://superuser.com/questions/989385/alsa-base-conf-missing-in-new-raspberry-pi-raspbian-jesse

**Comment by printgeek** [comment]
@Sacro524 That method may work, too. I found 2 or 3 different solutions yesterday before deciding on that one. I liked that it re-ordered the cards, not just made the USB output default, which fixed issues in other scripts that were on my pi. Also, I am using the minimal Raspbian Jessie distro.

**Comment by Bantammenace** [comment]
I resolved this by making sure the USB Audio Adapter and attached speaker and mic were working correctly on a fresh install of Jessie before following the guide. I installed Audacity to check that they were both working.

**Comment by Bantammenace** [comment]
I spoke too soon. That didn't work on reboot

**Comment by elstryan** [comment]
@Bantammenace 
After rebooting did you try looking at the alsa.conf file referenced in @Sacro524's post and make sure that your USB adapter is re-ordered to be the default?

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
