### ISSUE TITLE
ERROR com.amazon.alexa.avs.AVSApp - An error occured creating speech request

### ISSUE THREAD

**Issue by rkrmpg** [amzn/alexa-avs-raspberry-pi#53]
The moment I press the Start Listening button things crash with the following message 

>  [AWT-EventQueue-0] ERROR com.amazon.alexa.avs.AVSApp - An error occured creating speech request
> java.lang.NullPointerException

Spent a long time trying to troubleshoot this and have not been able to figure out the cause of the error and the fix. 

Anyone else experience this error and been able to resolve?

Full java exception attached.

Thanks in advanced for ideas.

[exception.txt](https://github.com/amzn/alexa-avs-raspberry-pi/files/192683/exception.txt)

**Comment by gpetroski** [comment]
I get the same exception

21:23:01.261 [AWT-EventQueue-0] ERROR com.amazon.alexa.avs.AVSApp - An error occured creating speech request
java.lang.NullPointerException
	at com.amazon.alexa.avs.AudioCapture.startCapture(AudioCapture.java:74) ~[classes/:?]
	at com.amazon.alexa.avs.AudioCapture.getAudioInputStream(AudioCapture.java:56) ~[classes/:?]

**Comment by gpetroski** [comment]
Its the microphone, verify you have it configured correctly.

**Comment by stiivik** [comment]
@gpetroski what do You mean by configured correctly? For instance i am using external usb soundcard to connect speakers and microphone. Doesn't matter how i try, i still get the error so i must be doing something wrong.

**Comment by vlasov01** [comment]
@stiivik Please check if the user you are using is a member of audio group.
If it is not the case you can run:
`sudo usermod -a -G audio <USERID>`

**Comment by stiivik** [comment]
@vlasov01 thanks I'll try this later today and update on status

**Comment by stiivik** [comment]
I'm not sure, but i guess i wasn't a member of the audio group, but i still could run it with the errors this time. The thing that worked for me was configuring .asoundrc with "nano ~/.asoundrc". By default there is this in the file:
`pcm.!default {
   type hw
   card 0
}`
I commented all this out and instead wrote this:
`pcm.!default {
   type plug
   slave {
      pcm "plughw:1.0"
   } 
}

ctl.!default {
   type hw
   card 1
}`

Since i'm using USB soundcard, this works for me as the "plughw" command changes the input format accordingly to what the application You're running requests. I also disabled the default pi soundcard so the apps wouldn't get confused. I did this by running "nano /boot/config.txt" scrolling to the end and comment the line "dtparam=audio=on". By doing all this, my alexa ran with errors, but worked perfectly after chaning my mic's volume a little bit higher. @vlasov01 when i ran the audio group command, i got alexa to run without any errors, so i guess it should be now as good as it gets, so thank You. All the other rep for the changes goes actually to adafruit Tony D, as he made a quite detailed video about potential problems in this project and explaining how and why. The video can be found here [https://www.youtube.com/watch?v=6fAdBehSYiA](url)

**Comment by vlasov01** [comment]
@stiivik I'm glad it works for you!

**Comment by ajotwani** [comment]
@rkrmpg can you please confirm if you are still having this issues?

**Comment by Ikol18** [comment]
Guys please help
Everything is setup perfectly with oracle java 8, maven ,node and everything
When I click on start listening the bar indicates its listening but when I press stop its not giving output
please help me
useful info:
using rpi2
usb sound card with mic input and speaker output(both are in working condition)
node v 5.10.0 and npm v3.8.3

**Comment by ajotwani** [comment]
@Ikol18 do you hear the audio cue when you click "Start listening"?

**Comment by Ikol18** [comment]
When I click on start listening the bar starts moving as if its listening but when I press stop I don't get any response

**Comment by elstryan** [comment]
@Ikol18 can you check your log file and post if there are any errors? (The log file application.log can be found under logs folder in the same directory that you run mvn exec:exec). Also +1 to ajotwani's question - do you hear the audio cue when you press start listening?

**Comment by Ikol18** [comment]
@elstryan Thanks for reply but I had found the solution the same day posted the question

**Comment by shaolinkhoa** [comment]
Hi all,
I have the same error in #213 
Would you mind helping me ?

**Comment by tweaty100** [comment]
@Ikol18  @ajot @elstryan @stiivik  @rkrmpg  i am also facing the same issue will you please help me how you solved this?please help me as i am badly stuck in this i am using earphones mic (which come with phone)? will it work ?i am not even able to hear the audio cue even when i enter start listening? 

Thanks in advance
