### ISSUE TITLE
Controlling Spotify is not supported?

### ISSUE THREAD

**Issue by RadianM** [amzn/alexa-avs-raspberry-pi#57]
I successfully linked my Spotify account on [http://alexa.amazon.com/](url) but the Music & Books section reports "App Support Unavailable". Almost everything else I tried works amazingly well - especially IFTTT triggering. Is there a reason Spotify control is out of bounds?

**Comment by bogdanripa** [comment]
Same problem here. Amazon books and iHeartRadio work just fine, but when I try to play an Amazon Prime station or Spotify it won't work.

Also, I manage to make it work on a Raspberry Pi 1.

**Comment by jonstuebe** [comment]
+1

**Comment by keleric** [comment]
Spotify is not currently supported on AVS. Amazon prime should work though - are you sure you're signed in with a Prime account?

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!

**Comment by snrlaxx** [comment]
Is there any other question related with this? 

I have the same problem and can't solve it...

Thanks!

**Comment by cthulu** [comment]
Is there anything new about this? I don't have Echo but wanted to try linking my AVS RpBI to Spotify at alexa.amazon.com but I only get the option to setup a device (which I don't have :( )

**Comment by eliogi** [comment]
Any news? I've built my Alexa device with RaspPi, but I'd like to connect my Spotify account... is this possible right now? Thanks.

**Comment by HappySock** [comment]
I have lots of apps showing this same problem.

**Comment by eliogi** [comment]
Hi @HappySock I've received from my last comment, several updates from Amazon about Alexa development frameword and libraries. Have you downloaded the latest version? (one update is about 3 days ago).
Finally I moved my attention (and my time) to AWS Cloud Services, and I've finally decided to buy Echo Dot in USA.

**Comment by HappySock** [comment]
it's related to your login status as far as I can tell. check out my other post for details: https://github.com/alexa/alexa-avs-sample-app/issues/906

**Comment by HappySock** [comment]
@eliogi if you like music at all you will really appreciate the echo over the dot. plus they are on sale right now for $99, deeper discount than they have ever put on. https://www.amazon.com/gp/product/B00X4WHP5E/ref=as_li_ss_tl?ie=UTF8&th=1&linkCode=ll1&tag=zone29-20&linkId=229554abf1c952ac07a9d2a104598afc

**Comment by eliogi** [comment]
Thanks @HappySock !
I've already bought my device but here in Italy I can only listen TuneLn radio.
Spotify is disabled and I can't enable it and Amazon Prime Music is available only if you pay with an American Credit Card (I don't have it). I really don't understand why.

**Comment by HappySock** [comment]
Try a proxy, you can spoof being here in the us.

And many folks use the prepaid credit cards to get around the card 
issue. Why in this global era this is still a problem I have no clue. I 
bet it's all about financial laws.

------ Original Message ------

**Comment by HappySock** [comment]
Oh, and the proxy will open up the world of netflix to you. As far as I 
know the US netflix library is much bigger than anywhere else.

------ Original Message ------

**Comment by eliogi** [comment]
Hi @HappySock I've used a VPN for Netflix and it works fine. But Amazon has some deeper check and so I can't enable spotify as well but... The idea of pre-paid credit card is a good idea. I want to try it in order to buy amazon unlimited music. I hope it will work :)
Thanks so much !

**Comment by HappySock** [comment]
Many of you may not know or remember who this is. If you don't, That's 
ok.  It happens. I'm sorry to have bothered you.

This isn't a chain letter. This is me, Jeff Legere, former medic, now 
disabled vet. I've served with some of you, I've gamed with some of you, 
I've probably pissed a some of you off (But I hope you can look past 
that), or perhaps I just did business with some of you. I don't know. I 
am reaching out to everyone I can.

Those that do remember me. I hope you will take a moment.

My mom is dying. I am trying to stop it and I need help, I can't do it 
alone. I don't know of any right way to ask this of anyone. We just 
don't have the money. She has cancer and her insurance just isn't 
covering the treatment in any meaningful way.

She's been diagnosed with metastatic choroidal melanoma which is a fancy 
way of saying she has a nasty type of cancer that started in her eye and 
has spread. It's in her spine and her lungs and her liver.

After insurance her medication is going to be $4,000 every 3 weeks. 
That's what the two of us make together in a month before any bills.

So far I have only found one program that *MAY* be able to help with one 
of the 5 medications in the treatment plan. And we don't know how long 
before we find out if they will.

https://www.gofundme.com/curing-her-cancer

I hope some of you can help, I hope at least a few of you will pass this 
on instead of just deleting this.
