### ISSUE TITLE
syntex for node version

### ISSUE THREAD

**Issue by bill-orange** [amzn/alexa-avs-raspberry-pi#66]
Someone check me on this.  

Step 2.5 starts with a version check on Node to see if it is installed.  
node —version
> command not found

That is a copy and paste from the readme.  When I copy and paste into putty on my PI, I get an error. (I am up and running under Jessie. Node is installed)

To get the version, I type:
Node --version
Two dashes, if you look close.  Looking at the text of the readme, the dash looks unusually long. I am not sure what is going on here.  But shouldn't the syntax in the readme be two dashes as in my second example?

This issue could lead folks to thinking node is not installed when it actually is.

**Comment by gregwa1953** [comment]
@bill-orange ,
Many web-based apps automatically change the double dash into a long single one.  When that happens most people forget or don't know that it is happening and don't mention that the dash is doubled.
I learned this the hard way.  Now (whenever I remember to) I mention that it would be a double dash rather than a single one.  

Many command line programs have a single dash version that uses the first letter of the command.  In your case it would be `node -v`.

The author, however, is probably using the verbose mode to avoid confusion to those who are fairly new at all this and simply forgot to mention that it was a double dash.

Hope this helps.

**Comment by bill-orange** [comment]
That did help.  Your answer makes perfect sense.  I suppose the readme should be revised to use  node -v . Most people will be using cut and paste.

**Comment by gregwa1953** [comment]
I, as an author, have fallen into this trap more times than I want to admit.
Glad that I was able to help.

Greg

**Comment by ajotwani** [comment]
Updated ReadMe to use the -v option for checking node version - https://github.com/amzn/alexa-avs-raspberry-pi/commit/646ef76d35747bd3dd86872b5a7f9c90accf939d
