### ISSUE TITLE
Multiple projects on RP

### ISSUE THREAD

**Issue by TylonHH** [amzn/alexa-avs-raspberry-pi#71]
Hi,
How can I use this project parallel to other projects? For example with kodi on openelec?
I don't want to control other projects or else, I just wanna save an other raspberry.

**Comment by bill-orange** [comment]
This interests me too.  I have a PI weather station in the living room somewhat strategically located.  I think that rather than running kodi as a stand alone you would get alexa up and running, then load kodi with apt-get install.  http://kodi.wiki/view/HOW-TO:Install_Kodi_on_Raspberry_Pi#Raspbian

There may turn out to be library conflicts.  I would duplicate the alexa SD before trying the kodi load.

**Comment by ProfessionalParanoid** [comment]
I've got mine running on a Magic Mirror https://www.raspberrypi.org/blog/magic-mirror/   I'll be working on a motion sensor trigger (vice a physical button) so a wave of a hand in a strategic location will trigger the Alexa.  
![img_4815](https://cloud.githubusercontent.com/assets/18242343/14231739/579ddebc-f95c-11e5-998c-2466976ce34e.JPG)

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
