### ISSUE TITLE
Problem starting client

### ISSUE THREAD

**Issue by mikefromphoebus** [amzn/alexa-avs-raspberry-pi#77]
When I try to upgrade the Java version (./install-java8.sh) I get "This OS is not Raspian. Exiting..."  Everything was going fine until this step.

**Comment by dmarkscouk** [comment]
I'm not expert (in fact a complete beginner), but I'm guessing your might be doing this through shh on a remote machine? If so maybe try this through VNC using the terminal on the raspberry pi.

**Comment by mikefromphoebus** [comment]
Nope.  I'm running TightVNC on the Pi and connecting via the VNC client.

**Comment by CaptainFiasco** [comment]
I had the same problem.  Looking at the install-java8.sh it was bombing out on the OS test, grepping the output of lsb_release for Raspian when it was returning Debian.  Changed the test to look for Debian and it worked fine.

I have an early Raspi 2, installed from NOOBS and regularly updated through apt-get but still on wheezy.  Maybe that's the problem?

**Comment by xozai** [comment]
I am encountering this issue.  I am running wheezy too.  I had tried this with Jessie, and I got farther along, but then encountered a different issue, so I started over with wheezy and encountered this issue.

**Comment by sasherm13** [comment]
Has anyone figured out a way around this?  I am using wheezy and cant get past this.

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
