### ISSUE TITLE
Running on Android?

### ISSUE THREAD

**Issue by Taconut** [amzn/alexa-avs-raspberry-pi#87]
Hi! From the looks of this project, it shouldn't be much trouble to get this thing to work on Android. There are already Node.js ports for Android and PTT could be replaced by hooking into the "OK Google" intent. And the

The only thing I see stopping someone from running this on Android is the Java client. But what does it actually do? Could it be ported to an APK? Assuming I can get the server running on localhost, how much work would it be to replace Google Now with Amazon Echo on my phone? I should be able to override the OK Google trigger with any function in any app on my phone.

**Comment by Taconut** [comment]
Also, as a side note, it should be possible to get always on working with the raspberry pi using something like PocketSphinx to listen for a hotword. If I can't get this to work I might try that.

**Comment by keleric** [comment]
I recommend searching the Amazon forums. There are a number of posts about getting AVS to work on Android. Here's one: https://forums.developer.amazon.com/questions/10926/android-implementation.html

Good luck!

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
