### ISSUE TITLE
iOS companion app "An SSL error has occurred"

### ISSUE THREAD

**Issue by stanica** [amzn/alexa-avs-raspberry-pi#95]
How do I get the iOS companion app working? It's running on my phone but I get the SSL error whenever I try to connect.

**Comment by elstryan** [comment]
If you haven't already seen this: there is documentation of the iOS companion app here: https://developer.amazon.com/public/solutions/alexa/alexa-voice-service/docs/java-client-sample just click on the iOS tabs on that page. 

Did you run the generate.sh script? Make sure that the certificates that are generated as part of this script are in the xcode project when you run the iOS companion app on your phone.

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
